---
# tasks file for nginx_install
  - name: Installing nginx
    yum:
      name: nginx
      state: present
  - name: Changing Port
    template:
      src: "/home/ansible/os_patch/change_port.conf.j2"
      dest: "/etc/nginx/nginx.conf"
